### PR TITLE
Add support for mockery

### PR DESCRIPTION
**Pull request by AndreasMalecki**
Hello @Haehnchen,

we've been using your plugin for a large PHP-based project for a while now. However, we are using Mockery as a mocking framework and were lacking support for it in IntelliJ/PHPStorm. Thus, we decided to create a few additions to your plugin such that it now could be used with Mockery, too. We added quite a bit of functionality, but we hope that you will find the time to review our suggested changes and finally merge our pull request. We are looking forward to hearing from you.

Best regards,
  Andreas Malecki

### CODE REVIEW

**Comment by Haehnchen** [comment]
:+1: thats a alot ;)

can you provide some screenshots so that i can extend readme and plugin description also ?

**Comment by AndreasMalecki** [comment]
Of course. But it may take until Monday. Do you have a specific functionality in mind that these screenshots should cover? Which theme should we use/should they be similar to the existing ones?

**Comment by colpusm** [comment]
Here are some screen shots using Mockery support:

annotate private method
autocomplete expects
autocomplete generated partial
autocomplete in array hash
inspector highlight
inspector result new syntax
inspector result
inspector settings

**Comment by Haehnchen** [comment]
:+1: will ship this with a new release soon

**Pull request merged**
